/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_generic_NativeAllocation
#define _Included_generic_NativeAllocation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generic_NativeAllocation
 * Method:    getObject
 * Signature: ()Object
 */
JNIEXPORT jobject JNICALL Java_generic_NativeAllocation_getObject
  (JNIEnv *, jobject);

  /*
 * Class:     generic_NativeAllocation
 * Method:    getNullObject
 * Signature: ()Object
 */
JNIEXPORT jobject JNICALL Java_generic_NativeAllocation_getNullObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif